### GET request to read all users
GET http://localhost:3000/api/v1/users

### POST request to create a new user 
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username": "ABC",
    "email": "abc@example.com",
    "password": "pass123"
}

### DELETE request to delete a user
DELETE http://localhost:3000/api/v1/users/1

